### ISSUE TITLE
Locks me out of Steam for half an hour if something goes wrong

### ISSUE THREAD

**Issue by gwemmie** [scholtzm/punk#27]
Kinda related to https://github.com/scholtzm/punk/issues/24

If Punk randomly has issues staying connected to Steam, maybe because of something faulty with Steam's servers (just like how my and other peoples' Steam clients will ocassionally be disconnected for a minute or so for no reason), it will keep trying to reconnect endlessly. The fact that it does that is fine, but the two undesirable results are baffling me:
1. It never actually manages to reconnect, even if my Steam clients can all connect just fine. Because of the 2nd result, I haven't had the chance to test if restarting it makes it reconnect properly.
2. The constant reconnecting, even though it supposedly can't access the server, causes Steam to lock me out of logging in from ANY client (both Punk and the client itself) for about 30 minutes, probably because it thinks I'm being brute-force hacked. I can't use Punk until we fix this, and that sucks.

I used Punk for the first time all day yesterday and for about 5 hours today, and it never had this problem. Since then, it's had this problem twice in 6 hours (from about 5PM to 11PM). Given that timing, maybe the attached log can help us figure out what's going on.

[punk.log.txt](https://github.com/scholtzm/punk/files/179145/punk.log.txt)

**Comment by scholtzm** [comment]
Thank you for this bug report. I had 2 disconnects yesterday but Punk managed to reconnect correctly both times instantly.

Thank you for providing the log. Are you using Punk alongside other client _with the same account_ by any chance?

The lock out itself is definitely caused by the "brute force" effect.

**Comment by gwemmie** [comment]
Yes, I am! In fact, that's probably the pattern. The period of issues happened around when I was trying to run it alongside the client. They're not running on the same computer, though.

**Comment by scholtzm** [comment]
I know what the issue is and I have a quick fix in mind, however it's far from ideal - it will force you to relogin. It will be available on Sunday unless I figure out better solution.

**Comment by gwemmie** [comment]
By relogin, do you mean steam --reset and rm -rf ~/.config/chromium/Punk? Or do you just mean logging in again on the app?

**Comment by scholtzm** [comment]
It will show you the login screen where you will have to input your username and password again.

**Comment by scholtzm** [comment]
Sorry for the delay, but I needed to write a packaging script before doing another release.
The patch for this bug is availabe in Punk v0.2.1.

https://github.com/scholtzm/punk/releases/tag/v0.2.1
