### ISSUE TITLE
login error:InvalidePassword

### ISSUE THREAD

**Issue by SergioGlorias** [scholtzm/punk#38]
I downloaded the client and whenever I try to log in with the steam account of the invalid password error

**Comment by SergioGlorias** [comment]
It seems that after a long wait time I managed to log in

**Comment by andrewda** [comment]
Probably a Steam issue – they often return InvalidPassword when something goes wrong internally.

**Comment by scholtzm** [comment]
This could have been caused by:
1. Providing invalid password
2. Providing invalid 2FA code too many times and then getting throttled
3. Steam having some issue

Either way, seems like the issue has been resolved. 👍
