### ISSUE TITLE
No line breaks in chat logs using default text editor

### ISSUE THREAD

**Issue by mxamber** [scholtzm/punk#39]
I tried the program today for the purpose of having chatlogs created automatically (instead of having to copy everything manually), and when I checked the log, I found that it had no line breaks when opened with the default text editor (notepad.exe). Like, none at all. Neither between posts, nor line breaks within one post. It does work when using an alternative editor, like npp.

I've no idea whether this is an issue with the Windows text editor or a problem with Punk. My best guess is that you developed the program on Mac or Linux and those OS use a different way to encode line breaks than Windows does?

![punk line breaks](https://user-images.githubusercontent.com/13611718/27994063-4f3d1168-64b6-11e7-96af-845a0af5957e.PNG)

![punk no line breaks](https://user-images.githubusercontent.com/13611718/27994066-546e2d2a-64b6-11e7-86be-2c2626c21126.PNG)

**Comment by scholtzm** [comment]
Yes, indeed. Punk uses `\n` for line breaks which is not displayed properly when using standard Notepad.exe.

For the time being, you can use some other editor, e.g. Notepad++.

I'll think about using CRLF on Windows instead of LF.

**Comment by scholtzm** [comment]
Just looking at it right now, this will be a very easy fix:

https://nodejs.org/api/os.html#os_os_eol
https://github.com/scholtzm/punk/blob/master/src/plugins/chat-logger/index.js#L37

**Comment by scholtzm** [comment]
Fixed in https://github.com/scholtzm/punk/commit/4fdd4ea787a9114c205cf36f292c7e1113ea987e
