### ISSUE TITLE
Resizing "<textarea>"-Chat-Input-Textfield on macOS breaks UI

### ISSUE THREAD

**Issue by SamuelSchepp** [scholtzm/punk#43]
Resizing the Chat-Input-Textfield by draging the handler on the bottom right causes the whole UI to break and creates a horizontal scroller in the chatview.

**Comment by scholtzm** [comment]
Just curious, could you please provide a screenshot?

I'm unable to resize chat message text area and I'm also using macOS. 🤔

**Comment by SamuelSchepp** [comment]
It has a handlebar in the bottom left corner.

![screenshot 2017-11-13 17 58 28](https://user-images.githubusercontent.com/11752441/32738447-41d29e8a-c89d-11e7-91d4-15479da23ca2.png)

**Comment by scholtzm** [comment]
Interesting. I see the handle but I can't click it and drag it on my computer. Weird...

Thanks for the report and subsequent pull request.

**Comment by SamuelSchepp** [comment]
Thanks for merging. You can drag it, while the mouse cursor is still the text cursor. Btw: Thanks so much for this client! The original is garbage.
