### ISSUE TITLE
Unable to close "Add Friend Dialog"

### ISSUE THREAD

**Issue by SamuelSchepp** [scholtzm/punk#48]
I accidentally opened this Dialog and was only able to close it by quitting.
PR #47

**Comment by scholtzm** [comment]
I believe I accidentally commented this out in https://github.com/scholtzm/punk/commit/87af8cac391db57976bc41382da6fd26f98e72d5 🤔 

I did notice this but only uncommented it in `switch-to-steam-user` branch which will be merged soon to master. Thanks for the PR.
